M48
; DRILL file {KiCad 7.0.1} date Mon Jul 17 09:13:57 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-17T09:13:57+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X3.761Y-3.5463
X3.761Y-3.7372
T2
X3.6417Y-3.5344
X3.6417Y-3.749
T3
X3.7402Y-4.7047
X5.4921Y-4.7047
T0
M30
